# Generated by Django 5.2.1 on 2025-05-27 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_cam', models.CharField(max_length=100)),
                ('ip_cam', models.GenericIPAddressField(blank=True, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('cftv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.cliente')),
            ],
        ),
    ]
