# Generated by Django 5.2.1 on 2025-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_cftv', models.CharField(max_length=100)),
                ('ip_externo', models.CharField(max_length=100)),
                ('cloud_cftv', models.CharField(max_length=100)),
                ('grup_pessoas', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
