# Generated by Django 5.0.7 on 2025-06-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cftv',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel'),
            preserve_default=False,
        ),
    ]
