# Generated by Django 5.0.7 on 2025-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_cftv_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cftv',
            name='data_cadastro',
            field=models.DateField(),
        ),
    ]
