# Generated by Django 5.0.7 on 2025-06-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_central', models.CharField(max_length=255)),
                ('sensores_instalados', models.CharField(max_length=255)),
                ('grup_pessoas', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel')),
            ],
        ),
    ]
