# Generated by Django 5.2.1 on 2025-06-02 02:34

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey('cliente.ClienteModel', on_delete=models.CASCADE)),
                ('modelo_central', models.CharField(max_length=255)),
                ('sensores_instalados', models.CharField(max_length=255)),
                ('grup_pessoas', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField()),
            ],
        ),
    ]
