# Generated by Django 5.2.1 on 2025-05-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('telefone_responsavel', models.CharField(max_length=255)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField()),
            ],
        ),
    ]
